(()=>{'use strict';const $=id=>document.getElementById(id),data=AuditData,slides=EducationAudit.compile(data);let index=0,timer;window.presentationSlides=slides;const logoSrc='assets/logo.svg';slides.forEach((s,i)=>{const page=document.createElement('section');page.className='slide';page.setAttribute('aria-label',`${i+1}. ${s.title}`);page.dataset.page=i+1;s.elements.forEach(e=>{const el=document.createElement('div');el.className='el '+e.k;Object.assign(el.style,{left:e.x+'px',top:e.y+'px',width:e.w+'px',height:e.h+'px'});if(e.k==='text'){el.textContent=e.t;Object.assign(el.style,{fontSize:e.size+'px',fontWeight:e.bold?'700':'400',color:e.color,textAlign:e.align,lineHeight:e.size<=20?'1.2':'1.3'});if(e.url){const link=document.createElement('a');link.href=e.url;link.target='_blank';link.rel='noopener noreferrer';link.style.color='inherit';link.style.textDecoration='none';link.textContent=e.t;el.textContent='';el.appendChild(link)}}else if(e.k==='image'){const im=new Image();im.src=logoSrc;im.alt='CocoRobo';el.appendChild(im)}else if(e.k==='line'){el.style[e.h?'borderLeft':'borderTop']='1.5px solid '+e.color;if(e.arrow){el.textContent='▶';Object.assign(el.style,{color:e.color,fontSize:'13px',textAlign:'right',lineHeight:'0px'})}}else{el.style.background=e.fill;if(e.stroke)el.style.border='1.5px solid '+e.stroke;if(e.k==='ellipse')el.style.borderRadius='50%'}page.appendChild(el)});$('deck').appendChild(page)});
const pages=[...document.querySelectorAll('.slide')];function show(i,hash=true){index=Math.max(0,Math.min(slides.length-1,i));pages.forEach((p,j)=>{p.classList.toggle('active',j===index);p.setAttribute('aria-hidden',j===index?'false':'true')});$('counter').textContent=String(index+1).padStart(2,'0')+' / '+slides.length;$('section').textContent=slides[index].section;$('prev').disabled=index===0;$('next').disabled=index===slides.length-1;$('progress').style.width=(index+1)/slides.length*100+'%';document.title=slides[index].title+' · 辛海洋 Tony Xin';if(hash)history.replaceState(null,'','#'+(index+1))}window.goToSlide=n=>show(n-1);
function resize(){const b=$('stage').getBoundingClientRect();$('deck').style.transform=`scale(${Math.max(.05,Math.min((b.width-24)/1280,(b.height-24)/720))})`}
function openDialog(title){$('dialog-title').textContent=title;$('dialog-body').textContent='';if(!$('dialog').open)$('dialog').showModal()}
function toc(){openDialog('演讲目录 · 29页');const grid=document.createElement('div');grid.className='toc';slides.forEach((s,i)=>{const b=document.createElement('button');if(i===index)b.className='current';const n=document.createElement('b');n.textContent=String(i+1).padStart(2,'0');const t=document.createElement('span');t.textContent=s.title;b.append(n,t);b.onclick=()=>{$('dialog').close();show(i)};grid.appendChild(b)});$('dialog-body').appendChild(grid)}
function notes(){openDialog(`${String(index+1).padStart(2,'0')} · ${slides[index].title}`);const p=document.createElement('div');p.className='notes';p.textContent=slides[index].notes;$('dialog-body').appendChild(p);const r=document.createElement('div');r.className='sources';slides[index].refs.forEach(n=>{const q=data.references[n],item=document.createElement('p');item.textContent=`[${n}] ${q.title} ${q.detail} `;if(q.url){const a=document.createElement('a');a.href=q.url;a.textContent='查看来源';a.target='_blank';a.rel='noopener noreferrer';item.appendChild(a)}r.appendChild(item)});$('dialog-body').appendChild(r)}
function toast(t){$('status').textContent=t;$('status').style.display='block';clearTimeout(timer);timer=setTimeout(()=>$('status').style.display='none',6000)}
function fullscreen(){if(document.fullscreenElement)document.exitFullscreen?.();else if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>toast('此浏览器不支持全屏，可横屏浏览。'));else toast('此浏览器不支持全屏，可横屏浏览。')}
$('prev').onclick=()=>show(index-1);$('next').onclick=()=>show(index+1);$('overview').onclick=$('counter').onclick=toc;$('notes').onclick=notes;$('fullscreen').onclick=fullscreen;$('close').onclick=()=>$('dialog').close();window.addEventListener('keydown',e=>{if($('dialog').open||e.ctrlKey||e.metaKey||e.altKey)return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();show(index+1)}else if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();show(index-1)}else if(e.key==='Home')show(0);else if(e.key==='End')show(slides.length-1);else if(e.key.toLowerCase()==='n')notes();else if(e.key.toLowerCase()==='o')toc();else if(e.key.toLowerCase()==='f')fullscreen()});let tx,ty;$('stage').addEventListener('touchstart',e=>{tx=e.changedTouches[0].clientX;ty=e.changedTouches[0].clientY},{passive:true});$('stage').addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-tx,dy=e.changedTouches[0].clientY-ty;if(Math.abs(dx)>45&&Math.abs(dx)>Math.abs(dy)*1.3)show(index+(dx<0?1:-1))},{passive:true});window.addEventListener('resize',resize);window.addEventListener('hashchange',()=>show((parseInt(location.hash.slice(1),10)||1)-1,false));
async function loadPptx(){if(window.PptxGenJS||window.pptxgen)return window.PptxGenJS||window.pptxgen;for(const url of ['https://cdn.jsdelivr.net/npm/pptxgenjs@4.0.0/dist/pptxgen.bundle.js','https://unpkg.com/pptxgenjs@4.0.0/dist/pptxgen.bundle.js']){try{await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=url;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)});if(window.PptxGenJS||window.pptxgen)return window.PptxGenJS||window.pptxgen}catch(e){}}throw Error('导出组件未能载入，请检查网络后重试。')}
async function rasterLogo(){const img=new Image();img.src=logoSrc;await img.decode();const c=document.createElement('canvas');c.width=888;c.height=204;c.getContext('2d').drawImage(img,0,0,888,204);return c.toDataURL('image/png')}
$('export').onclick=async()=>{const button=$('export');button.disabled=true;button.textContent='正在导出…';try{const Pptx=await loadPptx();const p=await EducationAudit.makePptx(data,slides,await rasterLogo(),Pptx);await p.writeFile({fileName:'Beyond_Personalization_Paradox_Tony_29slides.pptx',compression:true});toast('PPT已生成，包含可编辑文字、图形和讲者备注。')}catch(e){toast(e.message);console.error(e)}finally{button.disabled=false;button.textContent='导出PPT'}};show((parseInt(location.hash.slice(1),10)||1)-1,false);resize();})();
