(function(){
'use strict';
const data=window.PP_BUILD(window.PP_CONTENT),deck=document.getElementById('deck'),stage=document.getElementById('stage'),frame=document.getElementById('frame');
const NS='http://www.w3.org/2000/svg',dom=[];
function element(e){
 const n=document.createElement('div');n.className='el';Object.assign(n.style,{left:e.x+'px',top:e.y+'px',width:e.w+'px',height:e.h+'px'});
 if(e.kind==='text'){n.classList.add('txt');n.textContent=e.text;Object.assign(n.style,{fontSize:e.size+'px',fontWeight:e.bold?'700':'400',color:e.color,textAlign:e.align,lineHeight:e.lh||1.24});}
 else if(e.kind==='rect'||e.kind==='ellipse')Object.assign(n.style,{background:e.fill,borderRadius:e.kind==='ellipse'?'50%':(e.r||0)+'px',border:e.stroke?'1px solid '+e.stroke:'none'});
 else if(e.kind==='image'){const img=new Image();img.src=window.PP_LOGO||e.src;img.alt='CocoRobo';n.append(img);}
 else if(e.kind==='line'){
  const pad=8,dx=e.w,dy=e.h,ax=dx<0?Math.abs(dx)+pad:pad,ay=dy<0?Math.abs(dy)+pad:pad,bx=dx<0?pad:dx+pad,by=dy<0?pad:dy+pad;
  Object.assign(n.style,{left:Math.min(e.x,e.x+dx)-pad+'px',top:Math.min(e.y,e.y+dy)-pad+'px',width:Math.abs(dx)+pad*2+'px',height:Math.abs(dy)+pad*2+'px'});
  const svg=document.createElementNS(NS,'svg');svg.setAttribute('width','100%');svg.setAttribute('height','100%');svg.style.overflow='visible';const line=document.createElementNS(NS,'line');for(const [k,v] of Object.entries({x1:ax,y1:ay,x2:bx,y2:by,stroke:e.color,'stroke-width':e.width}))line.setAttribute(k,v);svg.append(line);
  if(e.arrow){const a=Math.atan2(by-ay,bx-ax),z=8,p=document.createElementNS(NS,'polygon');p.setAttribute('points',`${bx},${by} ${bx-z*Math.cos(a)+z*.46*Math.sin(a)},${by-z*Math.sin(a)-z*.46*Math.cos(a)} ${bx-z*Math.cos(a)-z*.46*Math.sin(a)},${by-z*Math.sin(a)+z*.46*Math.cos(a)}`);p.setAttribute('fill',e.color);svg.append(p);}n.append(svg);
 }
 return n;
}
for(const s of data){const n=document.createElement('section');n.className='slide';n.setAttribute('aria-label',s.id+' '+s.title);n.style.background=s.background;n.dataset.slide=s.id;for(const e of s.elements)n.append(element(e));deck.append(n);dom.push(n);}
let current=0,reading=false;
const dlg=document.getElementById('dialog'),heading=document.getElementById('dialog-title'),body=document.getElementById('dialog-body');
function show(i,hash=true){current=Math.max(0,Math.min(data.length-1,i));dom.forEach((n,k)=>{n.classList.toggle('active',k===current);n.setAttribute('aria-hidden',reading?'false':String(k!==current));});document.getElementById('counter').textContent=String(current+1).padStart(2,'0')+' / '+data.length;document.getElementById('section').textContent=data[current].section;document.getElementById('progress').style.width=(current+1)/data.length*100+'%';document.getElementById('status').textContent='第'+(current+1)+'页：'+data[current].title.replace('\n','');if(hash)history.replaceState(null,'','#'+(current+1));document.title=data[current].title.replace('\n','')+' · 超越个性化悖论';}
function resize(){if(reading){const scale=Math.min(1,(innerWidth-24)/1280);frame.style.cssText='width:100%;height:auto';deck.style.transform='none';dom.forEach(n=>{n.style.transform='scale('+scale+')';n.style.marginBottom=(720*(scale-1)+20)+'px';});}else{dom.forEach(n=>{n.style.transform='';n.style.marginBottom='';});const scale=Math.min((stage.clientWidth-24)/1280,(stage.clientHeight-24)/720);frame.style.width=1280*scale+'px';frame.style.height=720*scale+'px';deck.style.transform='scale('+scale+')';}}
function notes(){heading.textContent=String(current+1).padStart(2,'0')+'  '+data[current].title.replace('\n','');body.className='notes';body.textContent=data[current].notes;dlg.showModal();}
function overview(){heading.textContent='目录 · 32页正文＋4页附录';body.className='toc';body.replaceChildren();for(const [i,s]of data.entries()){const b=document.createElement('button');b.textContent=String(i+1).padStart(2,'0')+'  '+s.title.replace('\n','');b.setAttribute('aria-current',String(i===current));b.onclick=()=>{show(i);dlg.close();if(reading)dom[i].scrollIntoView();};body.append(b);}dlg.showModal();}
function fullscreen(){if(document.fullscreenElement){document.exitFullscreen?.();}else if(document.documentElement.requestFullscreen){document.documentElement.requestFullscreen().catch(()=>notify('浏览器未允许全屏。'));}else notify('此浏览器不支持网页全屏，可使用横屏观看。');}
function notify(t){const n=document.getElementById('message');n.textContent=t;n.hidden=false;setTimeout(()=>n.hidden=true,6000);}
function save(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
function noteFile(){save(new Blob(['# '+window.PP_CONTENT.title+'\n\n商业案例版3.0 · 32页正文＋4页附录\n\n'+data.map(s=>'## '+String(s.id).padStart(2,'0')+'. '+s.title.replace('\n','')+'\n\n'+s.notes).join('\n\n')],{type:'text/markdown;charset=utf-8'}),'Personalization_Paradox_v3_Speaker_Notes.md');}
let loading=null;
function loadPptx(){if(window.PptxGenJS||window.pptxgen)return Promise.resolve();if(loading)return loading;loading=new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/pptxgenjs@4.0.0/dist/pptxgen.bundle.js';s.onload=()=>window.PptxGenJS||window.pptxgen?resolve():reject(new Error('导出组件未加载'));s.onerror=()=>reject(new Error('导出组件加载失败，请使用离线包中的PPT'));document.head.append(s);});return loading;}
function logoPNG(){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{const canvas=document.createElement('canvas');canvas.width=888;canvas.height=204;canvas.getContext('2d').drawImage(im,0,0,888,204);try{resolve(canvas.toDataURL('image/png'));}catch(e){reject(e);}};im.onerror=()=>reject(new Error('Logo未能加载'));im.src=window.PP_LOGO||'assets/cocorobo-navy.svg';});}
async function exportPptx(){const b=document.getElementById('export');b.disabled=true;b.textContent='正在导出…';try{await loadPptx();const logo=await logoPNG(),p=new (window.PptxGenJS||window.pptxgen)(),c=x=>x.replace('#','');p.defineLayout({name:'WIDE',width:13.333333,height:7.5});p.layout='WIDE';p.author='Haiyang Xin';p.company='CocoRobo';p.title=window.PP_CONTENT.title;p.subject='Purpose alignment, decision-authority alignment, participation integrity';p.lang='zh-CN';p.theme={headFontFace:'Noto Sans CJK SC',bodyFontFace:'Noto Sans CJK SC',lang:'zh-CN'};p.revision='3';for(const sd of data){const s=p.addSlide();s.background={color:c(sd.background)};for(const e of sd.elements){const pos={x:e.x/96,y:e.y/96,w:e.w/96,h:e.h/96};if(e.kind==='text')s.addText(e.text,{...pos,fontFace:'Noto Sans CJK SC',fontSize:e.size*.75,bold:e.bold,color:c(e.color),align:e.align,valign:'top',margin:0,paraSpaceAfterPt:0,paraSpaceBeforePt:0,lineSpacingMultiple:e.lh||1.24,isTextBox:true});else if(e.kind==='rect'||e.kind==='ellipse')s.addShape(e.kind==='ellipse'?p.ShapeType.ellipse:e.r?p.ShapeType.roundRect:p.ShapeType.rect,{...pos,fill:{color:c(e.fill)},line:e.stroke?{color:c(e.stroke),width:.8}:{color:c(e.fill),transparency:100},radius:(e.r||0)/96,rectRadius:(e.r||0)/96,adjustPoint:e.r?Math.min(.15,e.r/Math.min(e.w,e.h)):undefined});else if(e.kind==='image')s.addImage({...pos,data:logo});else if(e.kind==='line'){const rev=e.w<0||e.h<0;s.addShape(p.ShapeType.line,{x:Math.min(e.x,e.x+e.w)/96,y:Math.min(e.y,e.y+e.h)/96,w:Math.abs(e.w)/96,h:Math.abs(e.h)/96,flipV:(e.w<0)!==(e.h<0),line:{color:c(e.color),width:e.width*.75,beginArrowType:e.arrow&&rev?'triangle':undefined,endArrowType:e.arrow&&!rev?'triangle':undefined}});}}s.addNotes(sd.notes);}await p.writeFile({fileName:'Beyond_Personalization_Paradox_v3_36slides.pptx',compression:true});}catch(e){notify(e.message||'导出失败，请使用提供的PPT文件。');}finally{b.disabled=false;b.textContent='导出PPT';}}
document.getElementById('prev').onclick=()=>show(current-1);document.getElementById('next').onclick=()=>show(current+1);document.getElementById('counter').onclick=overview;document.getElementById('overview').onclick=overview;document.getElementById('notes').onclick=notes;document.getElementById('close').onclick=()=>dlg.close();document.getElementById('fullscreen').onclick=fullscreen;document.getElementById('export').onclick=exportPptx;document.getElementById('download-notes').onclick=noteFile;document.getElementById('print').onclick=()=>window.print();document.getElementById('reading').onclick=()=>{reading=!reading;document.body.classList.toggle('reader',reading);document.getElementById('reading').textContent=reading?'演讲模式':'阅读模式';resize();show(current,false);if(reading)dom[current].scrollIntoView();};
dlg.addEventListener('click',ev=>{if(ev.target===dlg){const r=dlg.getBoundingClientRect();if(ev.clientX<r.left||ev.clientX>r.right||ev.clientY<r.top||ev.clientY>r.bottom)dlg.close();}});
window.addEventListener('keydown',ev=>{if(dlg.open||ev.metaKey||ev.ctrlKey||ev.altKey)return;const k=ev.key;if(['ArrowRight','PageDown',' '].includes(k)){ev.preventDefault();show(current+1);}else if(['ArrowLeft','PageUp'].includes(k)){ev.preventDefault();show(current-1);}else if(k==='Home')show(0);else if(k==='End')show(data.length-1);else if(k.toLowerCase()==='n')notes();else if(k.toLowerCase()==='o')overview();else if(k.toLowerCase()==='f')fullscreen();});
let touch=null;stage.addEventListener('touchstart',ev=>{if(ev.touches.length===1)touch={x:ev.touches[0].clientX,y:ev.touches[0].clientY};},{passive:true});stage.addEventListener('touchend',ev=>{if(!touch||reading)return;const t=ev.changedTouches[0],dx=t.clientX-touch.x,dy=t.clientY-touch.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*2)show(current+(dx<0?1:-1));touch=null;},{passive:true});window.addEventListener('resize',resize);window.addEventListener('hashchange',()=>show((parseInt(location.hash.slice(1))||1)-1,false));document.fonts.ready.then(resize);show((parseInt(location.hash.slice(1))||1)-1,false);resize();
window.__deckData=data;window.__showSlide=show;window.__exportPptx=exportPptx;
})();
