window.deckTranslations = {
  "en": {
    "meta": {
      "lang": "en",
      "title": "From AI Tool Users to AI Agent Creators · 15-slide edition",
      "description": "How teachers learned to create and govern pedagogical AI agents while protecting human agency and student thinking.",
      "ogDescription": "Boundary Learning for teacher agency in AI-mediated classrooms."
    },
    "ui": {
      "support": "Supporting page ↗",
      "overview": "Overview",
      "fullscreen": "Fullscreen",
      "notes": "Notes",
      "select": "Select a slide",
      "close": "Close ×",
      "speakerNotes": "Speaker notes",
      "keyboard": "Keyboard",
      "keyboardHelp": "← / → navigate · Space next · O overview · F fullscreen · N notes · Home / End first / last",
      "closePlain": "Close",
      "emptyNote": "This slide has no notes."
    },
    "slides": []
  },
  "zh": {
    "meta": {
      "lang": "zh-CN",
      "title": "从 AI 工具使用者到 AI 智能体创设者 · 15页分享版",
      "description": "教师如何学习创设并治理教学 AI 智能体，同时保护人的能动性与学生思考。",
      "ogDescription": "面向 AI 介导课堂中教师能动性的边界学习。"
    },
    "ui": {
      "support": "辅助页面 ↗",
      "overview": "总览",
      "fullscreen": "全屏",
      "notes": "讲者备注",
      "select": "选择幻灯片",
      "close": "关闭 ×",
      "speakerNotes": "讲者备注",
      "keyboard": "键盘快捷键",
      "keyboardHelp": "← / → 切换幻灯片 · 空格键下一页 · O 打开总览 · F 全屏 · N 讲者备注 · Home / End 跳至首张 / 末张",
      "closePlain": "关闭",
      "emptyNote": "本页没有备注。"
    },
    "slides": [
      {
        "title": "从 AI 工具使用者 到  AI 智能体创设者",
        "html": "<div class=\"cover-logos\"><div class=\"cocorobo-brand \" role=\"img\" aria-label=\"CocoRobo\"><img class=\"cocorobo-symbol\" src=\"./assets/cocorobo-icon-white.svg\" alt=\"\"><img class=\"cocorobo-wordmark\" src=\"./assets/cocorobo-white.svg\" alt=\"\"></div><div class=\"event-lockup\"><span>PREPARED FOR</span><strong>UNESCO</strong><small>DIGITAL LEARNING WEEK 2026</small></div></div><div class=\"cover-copy\"><p class=\"kicker \">教师能动性 · 实践与研究</p><h1>从 AI 工具使用者<br>到 <em>AI 智能体创设者</em></h1><p class=\"lead\">支持教师创设 AI 智能体，并决定这些智能体如何参与学习。</p></div><div class=\"cover-meta\"><span>Haiyang Xin · CocoRobo Ltd.</span><span>Paris · 2026</span></div>",
        "note": "00:00–00:20 · 20s\n中文提示：开场：我是辛海洋。先讲四个实践，再讲研究。\n\nEnglish speaking script:\nGood morning. I’m Haiyang Xin from CocoRobo. We work with teachers to build AI learning agents. Today I will share four cases from Shenzhen. Then I will explain what our research has taught us.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 1. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "AI 如何参与，由谁决定？",
        "html": "<p class=\"kicker navy\">核心问题</p><h2>AI 如何参与，由谁决定？</h2><p class=\"short-lead\">当 AI 能够引导、评价和生成时，教师仍需掌握教学决策权。</p><div class=\"short-two\"><article><h3>1 · 实践视角</h3><p>我们如何支持教师创设和使用智能体？</p></article><article><h3>2 · 学术视角</h3><p>这告诉我们怎样理解教师能力与能动性？</p></article></div>",
        "note": "00:20–00:50 · 30s\n中文提示：核心问题：AI会引导和反馈，教师还能决定什么？\n\nEnglish speaking script:\nAI can guide students. It can ask questions and give feedback. But who decides what it should do? We want teachers to keep making these choices. They know their students and their teaching goals. I will first show how different groups support this work. Then I will turn to the research.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 2–3. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "用一年时间，反复创设、测试和改进",
        "html": "<p class=\"kicker navy\">1 · 实践视角 / 项目怎样开展</p><h2>用一年时间，反复创设、测试和改进</h2><div class=\"short-reach\"><strong>1,000+</strong><p>触达教师，覆盖深圳四个区及合作学校</p></div><div class=\"short-timeline\"><article><time>2025 年 4 月</time><h3>打基础</h3><p>提示词与首批教学智能体</p></article><article><time>2025 年 9 月</time><h3>扩展</h3><p>学科共同体与多智能体工作流</p></article><article><time>2026 年 4 月</time><h3>系统化</h3><p>设计痕迹与持续投入</p></article></div><p class=\"short-takeaway\">每一轮都为下一轮的培训与平台设计提供依据。</p>",
        "note": "00:50–01:20 · 30s\n中文提示：项目背景：一年、三轮；四个案例是不同场域，不是一条行政实施链。\n\nEnglish speaking script:\nOur programme ran for one year, with three rounds of teacher development. We started with prompts. We then moved to teaching agents and more complex designs. Each round helped us plan the next. The four cases show different settings in Shenzhen. They are examples of support, not steps in one single project.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 4–6. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "深圳：开放资源，也给教师创作机会",
        "html": "<p class=\"kicker navy\">1 · 实践视角 / 深圳市教育局</p><h2>深圳：开放资源，也给教师创作机会</h2><div class=\"field-layout field-city\"><div><div class=\"field-points\"><article><h3>提供共同入口</h3><p>深教AI整合了10款经审核入驻的学习平台。</p></article><article><h3>支持教师开发应用</h3><p>三届全市教师云应用开发大赛，吸引超过2,000名教师参与。</p></article></div></div><figure><img src=\"./assets/city-platform.webp\" alt=\"深教AI · 市级平台\"><figcaption>深教AI · 市级平台</figcaption></figure></div><p class=\"short-takeaway\"><span class=\"takeaway-label\">可借鉴的经验</span>提供工具入口，也创造让教师动手设计的机会。</p>",
        "note": "01:20–02:05 · 45s\n中文提示：深圳：共同入口＋审核平台＋教师应用大赛。启示：有工具，也要有创作机会。\n\nEnglish speaking script:\nFirst, the city level. Shenzhen built a shared platform called Shenjiao AI. It brings together ten learning platforms. Providers must pass a review before they join. The city also held three contests for teacher-made applications. More than two thousand teachers took part. So teachers had both access to tools and a chance to build something themselves. For other cities, the lesson is to connect access with teacher creation.\n\n[Sources]\n素材2.pptx, slides 1–2. Institutional source supplied by the presenter as the Shenzhen Municipal Education Bureau material.\n\nEvidence and interpretation:\nSlide 1 reports launch in August 2023, access for 1,191 primary and secondary schools, 10 approved learning platforms, and 依效付费. It does not define the payment metric. Slide 2 reports three teacher cloud-application contests from 2024, over 2,000 participating teachers and 93 selected works. Reach and selected works are implementation outputs, not estimates of learning effects.\nThe “Lesson to share” is our interpretation of the documented approach, not a measured causal finding."
      },
      {
        "title": "坪山：培养能够带领 AI 的教师",
        "html": "<p class=\"kicker\">1 · 实践视角 / 坪山区教育局</p><h2>坪山：培养能够带领 AI 的教师</h2><div class=\"field-layout field-district\"><div><div class=\"field-points\"><article><h3>三批教师，持续培养</h3><p>从编写提示词，走向创设自己的教学智能体。</p></article><article><h3>课堂仍由教师主导</h3><p>英语口语课中，AI提供反馈，教师确定评价标准。</p></article></div></div><figure><img src=\"./assets/pingshan-classroom.webp\" alt=\"坪山 · 小学英语口语课堂\"><figcaption>坪山 · 小学英语口语课堂</figcaption></figure></div><p class=\"short-takeaway\"><span class=\"takeaway-label\">可借鉴的经验</span>帮助教师设计 AI 支持，也帮助他们决定怎样使用。</p>",
        "note": "02:05–02:50 · 45s\n中文提示：坪山：三批教师，从提示词到智能体。课堂AI给反馈，教师定标准。\n\nEnglish speaking script:\nNext is Pingshan District. Its work covered three groups of teachers. The training moved from writing prompts to building teaching agents. The classroom example shows what this can look like. Students practise speaking English. AI gives quick feedback. Teachers set the standards. The lesson is to help teachers build AI support and decide how to use it. The district’s role goes beyond providing a tool.\n\n[Sources]\nAI-Empowered_Education（英文168）.pptx, slide 1. Supplied as the Pingshan District Education Bureau case. The existing programme timeline is documented in the original deck, slides 4–7.\n\nEvidence and interpretation:\nThe supplied slide describes three training cohorts, a progression from prompts to teacher-created agents, and a primary English speaking class with instant AI feedback and teacher-set standards. Its 1,000+ training figure is not used as a research sample or added to other reach figures. Awards and claims of national ranking are omitted. The slide mentions a 66-second field case; this talk uses the supplied still image and does not budget a video.\nThe “Lesson to share” is our interpretation of the documented approach, not a measured causal finding."
      },
      {
        "title": "荔园：让教师参与制定评价标准",
        "html": "<p class=\"kicker navy\">1 · 实践视角 / 福田区荔园教育集团</p><h2>荔园：让教师参与制定评价标准</h2><div class=\"field-layout field-group\"><div><div class=\"field-points\"><article><h3>共同形成标准</h3><p>专家初拟指标，教师参与评分，课题组复核定稿。</p></article><article><h3>转化、试用、再修改</h3><p>将标准转成AI分析工具，在课堂试用，并根据教师反馈修改。</p></article></div></div><figure><img src=\"./assets/liyuan-standards.webp\" alt=\"荔园 · 课堂观察标准的五步建设流程\"><figcaption>荔园 · 课堂观察标准的五步建设流程</figcaption></figure></div><p class=\"short-takeaway\"><span class=\"takeaway-label\">可借鉴的经验</span>让教师参与制定 AI 据以评价的标准。</p>",
        "note": "02:50–03:40 · 50s\n中文提示：荔园：专家初拟→教师评分→团队定稿→工具开发→课堂试用。重点是教师共同参与标准制定。\n\nEnglish speaking script:\nAt Liyuan Education Group, I want to highlight the way classroom standards were developed. Experts first drafted the criteria. Teachers then rated them. The team reviewed the results and agreed on the final set. These criteria were turned into an AI tool for classroom observation. The team tried it in real lessons and used teacher feedback to revise it. Here, teachers helped shape the standards that guide AI. Other school groups can learn from this shared design process.\n\n[Sources]\n集团AI成果展示(1).zip → 荔园教育集团AI教育成果展示-英文版.pptx, slide 3; Chinese version, slide 3 embedded process graphic. Teacher support described in slide 2 and PPT稿件中英文版.docx.\n\nEvidence and interpretation:\nThe five-stage process describes expert drafting of a four-level indicator system, scoring by about 50 teachers, finalization by a nine-person research group, AI model and tool development, and classroom testing with revision using teacher feedback. Do not present the design and trial process as established measurement validity. The support system also includes self-study micro-courses, group training, visiting coaching and technical Q&A. International recognition and pilot-school claims are not needed for this takeaway.\nThe “Lesson to share” is our interpretation of the documented approach, not a measured causal finding."
      },
      {
        "title": "宝安：让每个智能体各有明确分工",
        "html": "<p class=\"kicker navy\">1 · 实践视角 / 英语学科 · 罗敏老师</p><h2>宝安：让每个智能体各有明确分工</h2><div class=\"field-layout field-subject\"><div><div class=\"field-points\"><article><h3>T · 命题</h3><p>辅助教师设计情景化口语评价任务。</p></article><article><h3>A · 测练</h3><p>担任测练结合的AI口语考官。</p></article><article><h3>S · 匹配</h3><p>将评价活动与标准进行匹配。</p></article><article><h3>K · 反馈</h3><p>通过学习数据分析提供反馈。</p></article></div></div><figure><img src=\"./assets/luo-task.webp\" alt=\"罗老师的TASK多智能体工作流 · 可可乐博\"><figcaption>罗老师的TASK多智能体工作流 · 可可乐博</figcaption></figure></div><p class=\"short-takeaway\"><span class=\"takeaway-label\">可借鉴的经验</span>先明确教学方法，再给 AI 安排清楚的角色。</p>",
        "note": "03:40–04:30 · 50s\n中文提示：宝安罗敏老师：TASK先有教学方法，再分配命题、测练、匹配和反馈四个角色。不要把四角色讲成已验证的线性流程。\n\nEnglish speaking script:\nThe fourth case is from English teaching in Bao’an. Ms Luo developed a speaking assessment method called TASK. She then built a workflow with four AI agents. T helps design speaking tasks. A supports practice and assessment. S matches activities to the standards. K gives feedback from learning data. Each agent has a clear job. The lesson is to start with the teaching method. Then decide which parts AI can support.\n\n[Sources]\n案例PPT（罗老师）.pptx, slides 1–2. User identifies this as the Bao’an English subject case. The workflow screenshot credits 罗敏 (Luo Min), 宝安小学（集团）红树林外国语小学.\n\nEvidence and interpretation:\nTASK means Tasksheets, Assessments, Standards and Key competences. The material describes an oral-assessment model and a CocoRobo workflow with four agents: T supports task design; A combines oral practice and assessment; S matches activities to standards; K provides feedback using data analysis. The figure documents four roles, not a verified linear routing sequence. The talk describes intended functions, not measured assessment accuracy, fairness or student gains.\nThe “Lesson to share” is our interpretation of the documented approach, not a measured causal finding."
      },
      {
        "title": "生物探究：支持探索，保留判断",
        "html": "<p class=\"kicker navy\">1 · 实践视角 / 一个课堂案例</p><h2>生物探究：支持探索，保留判断</h2><div class=\"short-case\"><figure><img src=\"./assets/biology-inquiry.webp\" alt=\"Biology inquiry seminar\"><figcaption>生物探究研讨 · 福田荔园小学</figcaption></figure><div class=\"short-rows\"><article><h3>AI 提供什么</h3><p>辅助诊断，帮助改进探究设计。</p></article><article><h3>教师决定什么</h3><p>规定智能体可以提供哪些支持。</p></article><article><h3>学生保留什么</h3><p>形成自己的解释，作出最终判断。</p></article></div></div><p class=\"short-takeaway\">智能体支持探索，但不直接给出最终答案。</p>",
        "note": "04:30–05:05 · 35s\n中文提示：课堂落点：生物探究，AI支持设计，学生仍须解释和判断。实践到这里结束。\n\nEnglish speaking script:\nNow let us look at what this means for students. In this biology example, AI helped students improve an inquiry design. It did not give the final answer. Students still had to explain their ideas and make a judgment. The teacher decided how much help AI should give. This brings us to the purpose of all this support: better teaching decisions.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 8. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "我们怎样研究教师学习？",
        "html": "<p class=\"kicker \">2 · 学术视角 / 证据来自哪里</p><h2>我们怎样研究教师学习？</h2><div class=\"short-evidence\"><div class=\"cohort-number\"><strong>3</strong><p>批坪山教师，开展系统性研究</p></div><div class=\"short-rows\"><article><h3>设计证据</h3><p>智能体作品、工作流配置和修改记录</p></article><article><h3>参与证据</h3><p>平台日志与参与模式</p></article><article><h3>教师陈述</h3><p>问卷、展示和访谈</p></article></div></div><p class=\"short-limit\">这些数据支持对教师学习与参与的分析，尚不能建立学生学习成效的因果结论。</p>",
        "note": "05:05–05:40 · 35s\n中文提示：转学术：四个案例是实践例子；研究证据另来自坪山三批教师。研究不证明学生学习效果。\n\nEnglish speaking script:\nI will now turn to the research. The four cases are examples of practice. Our research evidence comes from three teacher groups in Pingshan. We studied their agents, design changes and platform use. We also used surveys and interviews. These data help us understand teacher learning. They do not prove that AI improved student learning.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 4, 9–10, 17. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings.\nThe four practice cases are not four research cohorts. As reported in the original deck, the research programme includes four accepted conference papers and an ongoing Boundary Learning synthesis. Related preprints: https://arxiv.org/abs/2605.13906 and https://arxiv.org/abs/2605.12934 ."
      },
      {
        "title": "创设智能体，让教学判断变得可见",
        "html": "<p class=\"kicker \">2 · 学术视角 / 发现一</p><h2>创设智能体，让教学判断变得可见</h2><p class=\"short-lead\">教师把教学判断变成可运行的设计，再通过测试和修改来检视。</p><div class=\"short-two\"><article><h3>让判断显性化</h3><p>说明智能体的角色、顺序和限制。</p></article><article><h3>检查实际表现</h3><p>从测试和设计修改中观察教学判断。</p></article></div><p class=\"short-takeaway\">AI-TPACK 可以通过设计痕迹来分析，并与教师自我报告相互补充。</p>",
        "note": "05:40–06:20 · 40s\n中文提示：发现一：做智能体，让教学判断变成可看、可试、可改的设计。\n\nEnglish speaking script:\nThe first finding is about learning by making. When teachers build an agent, they must explain their teaching choices. What should it do? What should it leave to the student? They can then test the agent and change the design. This makes their ideas easier to see and discuss. We can study what they build, as well as what they say.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 11, 13. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "持续创设，有赖持续支持",
        "html": "<p class=\"kicker dark-text\">2 · 学术视角 / 发现二</p><h2>持续创设，有赖持续支持</h2><div class=\"short-three\"><article><h3>积极创设者</h3><p>创设并修改</p></article><article><h3>浏览者</h3><p>观察与探索</p></article><article><h3>低参与者</h3><p>很少参与</p></article></div><p class=\"short-lead emphasis\">参加培训，并不意味着会持续创设。</p><p class=\"short-body\">研究提示：自主性、胜任感、关系感与学校支持，是理解持续投入的重要条件。</p>",
        "note": "06:20–07:00 · 40s\n中文提示：发现二：有人创设，有人浏览，有人很少参与。持续创设需要选择、信心、同伴与学校支持。\n\nEnglish speaking script:\nThe second finding is about continued use. Some teachers kept creating and revising agents. Others mainly looked around. Some took little part. Training alone did not make everyone an active creator. Our studies point to the need for choice, skills, a sense of belonging and school support. Teachers also need time and people they can turn to for help.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 12–13. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "边界学习：判断 AI 应如何参与",
        "html": "<p class=\"kicker \">2 · 学术视角 / 发展中的框架</p><h2>边界学习：判断 AI 应如何参与</h2><div class=\"short-framework\"><article><h3>任务边界</h3><p>哪里适合 AI，哪里需要人的努力？</p></article><article><h3>模型边界</h3><p>问题来自提示词、工作流，还是模型？</p></article><article><h3>教学责任</h3><p>哪些决策属于教师、学生或同伴？</p></article><article><h3>结构化配置</h3><p>把判断转化为角色、限制与介入时机。</p></article></div><p class=\"short-limit\">这是对教师判断的工作性综合框架，仍在发展中。</p>",
        "note": "07:00–07:45 · 45s\n中文提示：边界学习四问：任务适合吗？AI能做到吗？谁来决定？怎样设置？这是发展中的框架。\n\nEnglish speaking script:\nWe bring these ideas together in a working framework called Boundary Learning. It asks four questions. Is this a good task for AI? Can the AI do it well? Who should make the key decisions? How do we turn those choices into the agent’s roles and limits? The framework is still developing. Its focus is how teachers learn to decide where AI belongs.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 3, 14. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "好的 AI 设计，要保护学生的思考",
        "html": "<p class=\"kicker \">2 · 学术视角 / 设计启示</p><h2>好的 AI 设计，要保护学生的思考</h2><div class=\"short-frictions\"><article><h3>AI 过早给出答案</h3><p>先要求学生尝试，再提供反馈。</p></article><article><h3>AI 取代学生自己的表达</h3><p>先同伴评价，再用 AI 辅助修改。</p></article><article><h3>AI 让讨论提前结束</h3><p>限制或暂停 AI，让对话继续。</p></article></div><p class=\"short-takeaway\">教师需要有权延迟、约束或取消 AI 的参与。</p>",
        "note": "07:45–08:25 · 40s\n中文提示：设计启示：先尝试、先同伴、必要时暂停AI。保护学生要做的思考。\n\nEnglish speaking script:\nHere are three design choices that follow from this idea. If AI gives answers too soon, ask students to try first. If AI replaces their own words, ask for peer feedback first. If AI stops a useful discussion, pause it. These are ways to protect student thinking. Teachers need the power to make these choices. Sometimes good AI use means using less AI.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 15. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "教育系统可以抓住三个重点",
        "html": "<p class=\"kicker navy\">对教师专业学习的启示</p><h2>教育系统可以抓住三个重点</h2><ol class=\"short-actions\"><li><h3>围绕创设组织学习</h3><p>让教师创设、测试并修改教学智能体。</p></li><li><h3>评价设计与修改过程</h3><p>以作品和过程痕迹补充自我报告。</p></li><li><h3>提供持续支持，保障教师决策权</h3><p>提供时间和同伴支持，允许教师限制 AI。</p></li></ol>",
        "note": "08:25–08:55 · 30s\n中文提示：三个建议：让教师动手做；看设计和修改；给时间、同伴和决策权。\n\nEnglish speaking script:\nFor education systems, I suggest three priorities. Let teachers build and test agents. Look at their designs and how they change them. Give teachers time, peer support and the right to limit AI. These are practical ways to support teacher agency: the ability to make choices and act on them.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 16. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "教师决定 AI 如何参与学习。",
        "html": "<div class=\"closing-copy\"><div class=\"cocorobo-brand closing-brand\" role=\"img\" aria-label=\"CocoRobo\"><img class=\"cocorobo-symbol\" src=\"./assets/cocorobo-icon-white.svg\" alt=\"\"><img class=\"cocorobo-wordmark\" src=\"./assets/cocorobo-white.svg\" alt=\"\"></div><p class=\"kicker \">带走的一句话</p><h2>教师决定 AI<br>如何参与学习。</h2><p class=\"closing-line\">教师能否决定：AI 何时应该向前一步，又何时应该退后？</p><div class=\"contact\"><b>Haiyang Xin</b><span>Founder &amp; CEO · CocoRobo Ltd.</span><a href=\"mailto:tony@cocorobo.cc\">tony@cocorobo.cc</a></div></div><div class=\"qr-panel\"><a href=\"https://cocorobo.hk/unesco2026/teacher/\" target=\"_blank\" rel=\"noopener\" aria-label=\"Supporting page\"><img src=\"./assets/supporting-page-qr.svg\" alt=\"QR code for supporting page\"></a><b>完整证据、研究与框架</b><span>cocorobo.hk/unesco2026/teacher/</span></div>",
        "note": "08:55–09:20 · 25s\n中文提示：结尾：AI何时介入、何时退后，教师应有权决定。致谢。\n\nEnglish speaking script:\nI will end with one simple question. Can teachers decide when AI should step forward, and when it should step back? Our work aims to help them do both. You can find the full studies on the supporting page. Thank you.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 18. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      }
    ]
  },
  "fr": {
    "meta": {
      "lang": "fr",
      "title": "Des utilisateurs d’outils d’IA aux créateurs d’agents d’IA · version 15 diapositives",
      "description": "Comment des enseignants ont appris à créer et gouverner des agents pédagogiques d’IA tout en préservant le pouvoir d’agir humain et la réflexion des élèves.",
      "ogDescription": "L’apprentissage des frontières au service du pouvoir d’agir enseignant dans les classes où l’IA intervient."
    },
    "ui": {
      "support": "Page d’accompagnement ↗",
      "overview": "Vue d’ensemble",
      "fullscreen": "Plein écran",
      "notes": "Notes",
      "select": "Choisir une diapositive",
      "close": "Fermer ×",
      "speakerNotes": "Notes de l’orateur",
      "keyboard": "Raccourcis clavier",
      "keyboardHelp": "← / → naviguer · Espace diapositive suivante · O vue d’ensemble · F plein écran · N notes · Home / End première / dernière",
      "closePlain": "Fermer",
      "emptyNote": "Aucune note pour cette diapositive."
    },
    "slides": [
      {
        "title": "Des utilisateurs d’IA aux  créateurs d’agents",
        "html": "<div class=\"cover-logos\"><div class=\"cocorobo-brand \" role=\"img\" aria-label=\"CocoRobo\"><img class=\"cocorobo-symbol\" src=\"./assets/cocorobo-icon-white.svg\" alt=\"\"><img class=\"cocorobo-wordmark\" src=\"./assets/cocorobo-white.svg\" alt=\"\"></div><div class=\"event-lockup\"><span>PREPARED FOR</span><strong>UNESCO</strong><small>DIGITAL LEARNING WEEK 2026</small></div></div><div class=\"cover-copy\"><p class=\"kicker \">POUVOIR D’AGIR ENSEIGNANT · PRATIQUE ET RECHERCHE</p><h1>Des utilisateurs d’IA<br>aux <em>créateurs d’agents</em></h1><p class=\"lead\">Aider les enseignants à créer des agents d’IA et à décider de leur participation aux apprentissages.</p></div><div class=\"cover-meta\"><span>Haiyang Xin · CocoRobo Ltd.</span><span>Paris · 2026</span></div>",
        "note": "00:00–00:20 · 20s\n中文提示：开场：我是辛海洋。先讲四个实践，再讲研究。\n\nEnglish speaking script:\nGood morning. I’m Haiyang Xin from CocoRobo. We work with teachers to build AI learning agents. Today I will share four cases from Shenzhen. Then I will explain what our research has taught us.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 1. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "Qui décide du rôle de l’IA ?",
        "html": "<p class=\"kicker navy\">NOTRE QUESTION</p><h2>Qui décide du rôle de l’IA ?</h2><p class=\"short-lead\">Quand l’IA guide, évalue et génère, les enseignants doivent garder la maîtrise des décisions pédagogiques.</p><div class=\"short-two\"><article><h3>1 · Pratique</h3><p>Comment accompagner la création et l’usage des agents ?</p></article><article><h3>2 · Recherche</h3><p>Que nous apprend ce travail sur les compétences et le pouvoir d’agir ?</p></article></div>",
        "note": "00:20–00:50 · 30s\n中文提示：核心问题：AI会引导和反馈，教师还能决定什么？\n\nEnglish speaking script:\nAI can guide students. It can ask questions and give feedback. But who decides what it should do? We want teachers to keep making these choices. They know their students and their teaching goals. I will first show how different groups support this work. Then I will turn to the research.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 2–3. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "Une année de création et d’amélioration",
        "html": "<p class=\"kicker navy\">1 · PRATIQUE / LE PROGRAMME</p><h2>Une année de création et d’amélioration</h2><div class=\"short-reach\"><strong>1 000+</strong><p>enseignants touchés dans quatre districts de Shenzhen et des écoles partenaires</p></div><div class=\"short-timeline\"><article><time>AVRIL 2025</time><h3>Fondations</h3><p>Prompts et premiers agents pédagogiques</p></article><article><time>SEPT. 2025</time><h3>Extension</h3><p>Communautés disciplinaires et flux multi-agents</p></article><article><time>AVRIL 2026</time><h3>Structuration</h3><p>Traces de conception et engagement durable</p></article></div><p class=\"short-takeaway\">Chaque étape a éclairé la formation et la plateforme pour la suivante.</p>",
        "note": "00:50–01:20 · 30s\n中文提示：项目背景：一年、三轮；四个案例是不同场域，不是一条行政实施链。\n\nEnglish speaking script:\nOur programme ran for one year, with three rounds of teacher development. We started with prompts. We then moved to teaching agents and more complex designs. Each round helped us plan the next. The four cases show different settings in Shenzhen. They are examples of support, not steps in one single project.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 4–6. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "Shenzhen : accès et possibilités de créer",
        "html": "<p class=\"kicker navy\">1 · PRATIQUE / BUREAU MUNICIPAL DE L’ÉDUCATION DE SHENZHEN</p><h2>Shenzhen : accès et possibilités de créer</h2><div class=\"field-layout field-city\"><div><div class=\"field-points\"><article><h3>Un point d’accès commun</h3><p>Shenjiao AI réunit 10 plateformes d’apprentissage agréées.</p></article><article><h3>Les enseignants créent des applications</h3><p>Trois concours municipaux ont réuni plus de 2 000 enseignants.</p></article></div></div><figure><img src=\"./assets/city-platform.webp\" alt=\"Shenjiao AI · plateforme municipale\"><figcaption>Shenjiao AI · plateforme municipale</figcaption></figure></div><p class=\"short-takeaway\"><span class=\"takeaway-label\">À retenir</span>Donner accès aux outils et offrir des occasions de créer.</p>",
        "note": "01:20–02:05 · 45s\n中文提示：深圳：共同入口＋审核平台＋教师应用大赛。启示：有工具，也要有创作机会。\n\nEnglish speaking script:\nFirst, the city level. Shenzhen built a shared platform called Shenjiao AI. It brings together ten learning platforms. Providers must pass a review before they join. The city also held three contests for teacher-made applications. More than two thousand teachers took part. So teachers had both access to tools and a chance to build something themselves. For other cities, the lesson is to connect access with teacher creation.\n\n[Sources]\n素材2.pptx, slides 1–2. Institutional source supplied by the presenter as the Shenzhen Municipal Education Bureau material.\n\nEvidence and interpretation:\nSlide 1 reports launch in August 2023, access for 1,191 primary and secondary schools, 10 approved learning platforms, and 依效付费. It does not define the payment metric. Slide 2 reports three teacher cloud-application contests from 2024, over 2,000 participating teachers and 93 selected works. Reach and selected works are implementation outputs, not estimates of learning effects.\nThe “Lesson to share” is our interpretation of the documented approach, not a measured causal finding."
      },
      {
        "title": "Pingshan : les enseignants aux commandes",
        "html": "<p class=\"kicker\">1 · PRATIQUE / BUREAU DE L’ÉDUCATION DE PINGSHAN</p><h2>Pingshan : les enseignants aux commandes</h2><div class=\"field-layout field-district\"><div><div class=\"field-points\"><article><h3>Former trois cohortes d’enseignants</h3><p>Passer des prompts à la création d’agents pédagogiques.</p></article><article><h3>Garder la maîtrise de l’enseignement</h3><p>En anglais, l’IA donne un retour. Les enseignants fixent les critères.</p></article></div></div><figure><img src=\"./assets/pingshan-classroom.webp\" alt=\"Pingshan · cours d’anglais oral au primaire\"><figcaption>Pingshan · cours d’anglais oral au primaire</figcaption></figure></div><p class=\"short-takeaway\"><span class=\"takeaway-label\">À retenir</span>Aider les enseignants à concevoir l’aide de l’IA et à en décider l’usage.</p>",
        "note": "02:05–02:50 · 45s\n中文提示：坪山：三批教师，从提示词到智能体。课堂AI给反馈，教师定标准。\n\nEnglish speaking script:\nNext is Pingshan District. Its work covered three groups of teachers. The training moved from writing prompts to building teaching agents. The classroom example shows what this can look like. Students practise speaking English. AI gives quick feedback. Teachers set the standards. The lesson is to help teachers build AI support and decide how to use it. The district’s role goes beyond providing a tool.\n\n[Sources]\nAI-Empowered_Education（英文168）.pptx, slide 1. Supplied as the Pingshan District Education Bureau case. The existing programme timeline is documented in the original deck, slides 4–7.\n\nEvidence and interpretation:\nThe supplied slide describes three training cohorts, a progression from prompts to teacher-created agents, and a primary English speaking class with instant AI feedback and teacher-set standards. Its 1,000+ training figure is not used as a research sample or added to other reach figures. Awards and claims of national ranking are omitted. The slide mentions a 66-second field case; this talk uses the supplied still image and does not budget a video.\nThe “Lesson to share” is our interpretation of the documented approach, not a measured causal finding."
      },
      {
        "title": "Liyuan : les enseignants contribuent aux critères",
        "html": "<p class=\"kicker navy\">1 · PRATIQUE / GROUPE SCOLAIRE LIYUAN, FUTIAN</p><h2>Liyuan : les enseignants contribuent aux critères</h2><div class=\"field-layout field-group\"><div><div class=\"field-points\"><article><h3>Définir les critères ensemble</h3><p>Des experts les proposent. Les enseignants les évaluent. L’équipe les finalise.</p></article><article><h3>Créer, tester et réviser</h3><p>Transformer les critères en outil d’analyse IA. Le tester en classe et recueillir les retours.</p></article></div></div><figure><img src=\"./assets/liyuan-standards.webp\" alt=\"Liyuan · cinq étapes pour l’observation des classes\"><figcaption>Liyuan · cinq étapes pour l’observation des classes</figcaption></figure></div><p class=\"short-takeaway\"><span class=\"takeaway-label\">À retenir</span>Associer les enseignants aux critères qui guident l’IA.</p>",
        "note": "02:50–03:40 · 50s\n中文提示：荔园：专家初拟→教师评分→团队定稿→工具开发→课堂试用。重点是教师共同参与标准制定。\n\nEnglish speaking script:\nAt Liyuan Education Group, I want to highlight the way classroom standards were developed. Experts first drafted the criteria. Teachers then rated them. The team reviewed the results and agreed on the final set. These criteria were turned into an AI tool for classroom observation. The team tried it in real lessons and used teacher feedback to revise it. Here, teachers helped shape the standards that guide AI. Other school groups can learn from this shared design process.\n\n[Sources]\n集团AI成果展示(1).zip → 荔园教育集团AI教育成果展示-英文版.pptx, slide 3; Chinese version, slide 3 embedded process graphic. Teacher support described in slide 2 and PPT稿件中英文版.docx.\n\nEvidence and interpretation:\nThe five-stage process describes expert drafting of a four-level indicator system, scoring by about 50 teachers, finalization by a nine-person research group, AI model and tool development, and classroom testing with revision using teacher feedback. Do not present the design and trial process as established measurement validity. The support system also includes self-study micro-courses, group training, visiting coaching and technical Q&A. International recognition and pilot-school claims are not needed for this takeaway.\nThe “Lesson to share” is our interpretation of the documented approach, not a measured causal finding."
      },
      {
        "title": "Bao’an : un rôle clair pour chaque agent",
        "html": "<p class=\"kicker navy\">1 · PRATIQUE / ANGLAIS · ENSEIGNANTE LUO MIN</p><h2>Bao’an : un rôle clair pour chaque agent</h2><div class=\"field-layout field-subject\"><div><div class=\"field-points\"><article><h3>T · Tâches</h3><p>Aider à concevoir les tâches d’expression orale.</p></article><article><h3>A · Pratique et évaluation</h3><p>Jouer le rôle d’examinateur oral.</p></article><article><h3>S · Critères</h3><p>Relier les activités aux critères.</p></article><article><h3>K · Retour</h3><p>Utiliser les données pour fournir un retour.</p></article></div></div><figure><img src=\"./assets/luo-task.webp\" alt=\"Le dispositif TASK de Mme Luo · CocoRobo\"><figcaption>Le dispositif TASK de Mme Luo · CocoRobo</figcaption></figure></div><p class=\"short-takeaway\"><span class=\"takeaway-label\">À retenir</span>Partir de la méthode pédagogique, puis définir les rôles de l’IA.</p>",
        "note": "03:40–04:30 · 50s\n中文提示：宝安罗敏老师：TASK先有教学方法，再分配命题、测练、匹配和反馈四个角色。不要把四角色讲成已验证的线性流程。\n\nEnglish speaking script:\nThe fourth case is from English teaching in Bao’an. Ms Luo developed a speaking assessment method called TASK. She then built a workflow with four AI agents. T helps design speaking tasks. A supports practice and assessment. S matches activities to the standards. K gives feedback from learning data. Each agent has a clear job. The lesson is to start with the teaching method. Then decide which parts AI can support.\n\n[Sources]\n案例PPT（罗老师）.pptx, slides 1–2. User identifies this as the Bao’an English subject case. The workflow screenshot credits 罗敏 (Luo Min), 宝安小学（集团）红树林外国语小学.\n\nEvidence and interpretation:\nTASK means Tasksheets, Assessments, Standards and Key competences. The material describes an oral-assessment model and a CocoRobo workflow with four agents: T supports task design; A combines oral practice and assessment; S matches activities to standards; K provides feedback using data analysis. The figure documents four roles, not a verified linear routing sequence. The talk describes intended functions, not measured assessment accuracy, fairness or student gains.\nThe “Lesson to share” is our interpretation of the documented approach, not a measured causal finding."
      },
      {
        "title": "Biologie : soutenir l’enquête et le jugement",
        "html": "<p class=\"kicker navy\">1 · PRATIQUE / UN EXEMPLE EN CLASSE</p><h2>Biologie : soutenir l’enquête et le jugement</h2><div class=\"short-case\"><figure><img src=\"./assets/biology-inquiry.webp\" alt=\"Biology inquiry seminar\"><figcaption>Séminaire de biologie · École primaire Liyuan, Futian</figcaption></figure><div class=\"short-rows\"><article><h3>Apport de l’IA</h3><p>Aider au diagnostic et affiner la démarche d’enquête.</p></article><article><h3>Décision de l’enseignant</h3><p>Définir l’aide que l’agent peut apporter.</p></article><article><h3>Responsabilité de l’élève</h3><p>Construire son explication et exercer son jugement.</p></article></div></div><p class=\"short-takeaway\">L’agent soutient l’exploration sans fournir la réponse finale.</p>",
        "note": "04:30–05:05 · 35s\n中文提示：课堂落点：生物探究，AI支持设计，学生仍须解释和判断。实践到这里结束。\n\nEnglish speaking script:\nNow let us look at what this means for students. In this biology example, AI helped students improve an inquiry design. It did not give the final answer. Students still had to explain their ideas and make a judgment. The teacher decided how much help AI should give. This brings us to the purpose of all this support: better teaching decisions.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 8. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "Comment avons-nous étudié l’apprentissage enseignant ?",
        "html": "<p class=\"kicker \">2 · RECHERCHE / LES DONNÉES</p><h2>Comment avons-nous étudié l’apprentissage enseignant ?</h2><div class=\"short-evidence\"><div class=\"cohort-number\"><strong>3</strong><p>cohortes étudiées systématiquement à Pingshan</p></div><div class=\"short-rows\"><article><h3>Conception</h3><p>Agents créés, flux de travail et révisions</p></article><article><h3>Participation</h3><p>Journaux de plateforme et formes d’engagement</p></article><article><h3>Parole enseignante</h3><p>Questionnaires, présentations et entretiens</p></article></div></div><p class=\"short-limit\">Ces données éclairent l’apprentissage et la participation des enseignants, sans établir un effet causal sur les acquis des élèves.</p>",
        "note": "05:05–05:40 · 35s\n中文提示：转学术：四个案例是实践例子；研究证据另来自坪山三批教师。研究不证明学生学习效果。\n\nEnglish speaking script:\nI will now turn to the research. The four cases are examples of practice. Our research evidence comes from three teacher groups in Pingshan. We studied their agents, design changes and platform use. We also used surveys and interviews. These data help us understand teacher learning. They do not prove that AI improved student learning.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 4, 9–10, 17. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings.\nThe four practice cases are not four research cohorts. As reported in the original deck, the research programme includes four accepted conference papers and an ongoing Boundary Learning synthesis. Related preprints: https://arxiv.org/abs/2605.13906 and https://arxiv.org/abs/2605.12934 ."
      },
      {
        "title": "Créer des agents rend la pédagogie visible",
        "html": "<p class=\"kicker \">2 · RECHERCHE / RÉSULTAT 1</p><h2>Créer des agents rend la pédagogie visible</h2><p class=\"short-lead\">Les enseignants traduisent leurs jugements en dispositifs exécutables, testables et révisables.</p><div class=\"short-two\"><article><h3>Expliciter le jugement</h3><p>Préciser le rôle, la séquence et les limites de l’agent.</p></article><article><h3>Examiner le fonctionnement</h3><p>Étudier les tests et les révisions pour analyser la pédagogie.</p></article></div><p class=\"short-takeaway\">Les traces de conception éclairent l’AI-TPACK, en complément des déclarations des enseignants.</p>",
        "note": "05:40–06:20 · 40s\n中文提示：发现一：做智能体，让教学判断变成可看、可试、可改的设计。\n\nEnglish speaking script:\nThe first finding is about learning by making. When teachers build an agent, they must explain their teaching choices. What should it do? What should it leave to the student? They can then test the agent and change the design. This makes their ideas easier to see and discuss. We can study what they build, as well as what they say.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 11, 13. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "La création durable demande un soutien continu",
        "html": "<p class=\"kicker dark-text\">2 · RECHERCHE / RÉSULTAT 2</p><h2>La création durable demande un soutien continu</h2><div class=\"short-three\"><article><h3>Créateurs actifs</h3><p>Créent et révisent</p></article><article><h3>Explorateurs</h3><p>Observent et découvrent</p></article><article><h3>Faible engagement</h3><p>Participent rarement</p></article></div><p class=\"short-lead emphasis\">La formation seule ne garantit pas une création durable.</p><p class=\"short-body\">Les études soulignent l’autonomie, la compétence, les relations et le soutien de l’établissement.</p>",
        "note": "06:20–07:00 · 40s\n中文提示：发现二：有人创设，有人浏览，有人很少参与。持续创设需要选择、信心、同伴与学校支持。\n\nEnglish speaking script:\nThe second finding is about continued use. Some teachers kept creating and revising agents. Others mainly looked around. Some took little part. Training alone did not make everyone an active creator. Our studies point to the need for choice, skills, a sense of belonging and school support. Teachers also need time and people they can turn to for help.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 12–13. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "Apprendre à définir le rôle de l’IA",
        "html": "<p class=\"kicker \">2 · RECHERCHE / UN CADRE ÉMERGENT</p><h2>Apprendre à définir le rôle de l’IA</h2><div class=\"short-framework\"><article><h3>Tâche</h3><p>Où l’IA est-elle utile ? Où l’effort humain est-il essentiel ?</p></article><article><h3>Modèle</h3><p>Le problème vient-il du prompt, du flux ou du modèle ?</p></article><article><h3>Responsabilité</h3><p>Quelles décisions relèvent des enseignants, élèves ou pairs ?</p></article><article><h3>Configuration</h3><p>Traduire ces jugements en rôles, limites et temporalité.</p></article></div><p class=\"short-limit\">Boundary Learning : une synthèse de travail encore en développement.</p>",
        "note": "07:00–07:45 · 45s\n中文提示：边界学习四问：任务适合吗？AI能做到吗？谁来决定？怎样设置？这是发展中的框架。\n\nEnglish speaking script:\nWe bring these ideas together in a working framework called Boundary Learning. It asks four questions. Is this a good task for AI? Can the AI do it well? Who should make the key decisions? How do we turn those choices into the agent’s roles and limits? The framework is still developing. Its focus is how teachers learn to decide where AI belongs.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 3, 14. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "Une bonne conception protège la réflexion",
        "html": "<p class=\"kicker \">2 · RECHERCHE / IMPLICATIONS POUR LA CONCEPTION</p><h2>Une bonne conception protège la réflexion</h2><div class=\"short-frictions\"><article><h3>L’IA répond trop tôt</h3><p>Demander un premier essai avant le retour.</p></article><article><h3>L’IA remplace la voix de l’élève</h3><p>Faire intervenir les pairs avant la révision avec l’IA.</p></article><article><h3>L’IA met fin à la discussion</h3><p>Limiter ou suspendre l’IA pour relancer le dialogue.</p></article></div><p class=\"short-takeaway\">Les enseignants doivent pouvoir retarder, limiter ou retirer la participation de l’IA.</p>",
        "note": "07:45–08:25 · 40s\n中文提示：设计启示：先尝试、先同伴、必要时暂停AI。保护学生要做的思考。\n\nEnglish speaking script:\nHere are three design choices that follow from this idea. If AI gives answers too soon, ask students to try first. If AI replaces their own words, ask for peer feedback first. If AI stops a useful discussion, pause it. These are ways to protect student thinking. Teachers need the power to make these choices. Sometimes good AI use means using less AI.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 15. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "Trois priorités pour les systèmes éducatifs",
        "html": "<p class=\"kicker navy\">IMPLICATIONS POUR LE DÉVELOPPEMENT PROFESSIONNEL</p><h2>Trois priorités pour les systèmes éducatifs</h2><ol class=\"short-actions\"><li><h3>Organiser l’apprentissage autour de la création</h3><p>Créer, tester et réviser des agents pédagogiques.</p></li><li><h3>Évaluer les conceptions et leurs révisions</h3><p>Associer artefacts, traces et autoévaluations.</p></li><li><h3>Soutenir les enseignants et leur pouvoir de décision</h3><p>Prévoir du temps, des pairs et le droit de limiter l’IA.</p></li></ol>",
        "note": "08:25–08:55 · 30s\n中文提示：三个建议：让教师动手做；看设计和修改；给时间、同伴和决策权。\n\nEnglish speaking script:\nFor education systems, I suggest three priorities. Let teachers build and test agents. Look at their designs and how they change them. Give teachers time, peer support and the right to limit AI. These are practical ways to support teacher agency: the ability to make choices and act on them.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 16. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      },
      {
        "title": "Les enseignants définissent le rôle de l’IA.",
        "html": "<div class=\"closing-copy\"><div class=\"cocorobo-brand closing-brand\" role=\"img\" aria-label=\"CocoRobo\"><img class=\"cocorobo-symbol\" src=\"./assets/cocorobo-icon-white.svg\" alt=\"\"><img class=\"cocorobo-wordmark\" src=\"./assets/cocorobo-white.svg\" alt=\"\"></div><p class=\"kicker \">À RETENIR</p><h2>Les enseignants<br>définissent le rôle de l’IA.</h2><p class=\"closing-line\">Les enseignants peuvent-ils décider quand l’IA doit intervenir et quand elle doit s’effacer ?</p><div class=\"contact\"><b>Haiyang Xin</b><span>Founder &amp; CEO · CocoRobo Ltd.</span><a href=\"mailto:tony@cocorobo.cc\">tony@cocorobo.cc</a></div></div><div class=\"qr-panel\"><a href=\"https://cocorobo.hk/unesco2026/teacher/\" target=\"_blank\" rel=\"noopener\" aria-label=\"Supporting page\"><img src=\"./assets/supporting-page-qr.svg\" alt=\"QR code for supporting page\"></a><b>Données, études et cadre complet</b><span>cocorobo.hk/unesco2026/teacher/</span></div>",
        "note": "08:55–09:20 · 25s\n中文提示：结尾：AI何时介入、何时退后，教师应有权决定。致谢。\n\nEnglish speaking script:\nI will end with one simple question. Can teachers decide when AI should step forward, and when it should step back? Our work aims to help them do both. You can find the full studies on the supporting page. Thank you.\n\n[Sources]\nOriginal 18-slide presentation, slide(s) 18. https://tonyxinvip.github.io/slides/teacher-agent-creators/ ; supporting evidence: https://cocorobo.hk/unesco2026/teacher/\n\nEvidence and interpretation:\nEvidence scope follows the original deck. Design implications are not additional experimental findings."
      }
    ]
  }
};
